services:
  pipeline:
    build:
      context: .
      dockerfile: docker/Dockerfile
    working_dir: /work
    volumes:
      - ./:/work
    command:
      [
        "all",
        "--config",
        "configs/config.docker.cpu.json",
        "--story",
        "stories/story.aws.ec2.json"
      ]
